name: CI/CD

concurrency: ci-${{ github.ref }}

on:
  workflow_dispatch:

  schedule:
#  - cron: "0/15 16-23,0-9 * * *" # “At every 15th minute from 0 through 59 past every hour from 16 through 23 and every hour from 0 through 9.”
  - cron: "15 16-23,0-9 * * *" # “At minute 15 past every hour from 16 through 23 and every hour from 0 through 9.”

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  call-workflow-nuget-autoupdate:
    uses: Digitalroot-Valheim/.github/.github/workflows/nuget.autoupdate.yml@main
    secrets:
      github-pat: ${{ secrets.AUTOMATED_DEPENDENCY_UPDATES_TOKEN }}
